language: cpp
compiler:
  - gcc
  - clang
before_install: "mkdir build; cd build;"
install: "cmake -G \"Unix Makefiles\" ../ && make"
script:
  >
    echo;
    echo '################################################################################';
    echo '# embedded.ref                                                                 #';
    echo '################################################################################';
    echo;
    ./refal2 ../tests/embedded.ref;
    echo;
    echo '################################################################################';
    echo '# matching.ref                                                                 #';
    echo '################################################################################';
    echo;
    ./refal2 ../tests/matching.ref;
    echo;
    echo '################################################################################';
    echo '# speed.ref                                                                    #';
    echo '################################################################################';
    echo;
    ./refal2 ../tests/speed.ref
branches:
  only:
    - master
    - develop
