language: cpp
compiler:
  - gcc
  - clang
before_install: "mkdir build; cd build;"
install: "cmake -G \"Unix Makefiles\" ../ && make"
script: "./refal2 ../tests/embedded.ref"
branches:
  only:
    - master
    - develop
