language: cpp
compiler:
  - gcc
  - clang
before_install: "mkdir build; cd build;"
install: "cmake -G \"Unix Makefiles\" ../ && make"
script:
  >
    echo;
    echo '################################################################################';
    echo '# embedded.ref                                                                 #';
    echo '################################################################################';
    echo;
    ./refal2 ../tests/embedded.ref;
    echo;
    echo '################################################################################';
    echo '# matching.ref                                                                 #';
    echo '################################################################################';
    echo;
    ./refal2 ../tests/matching.ref;
    echo;
    echo '################################################################################';
    echo '# speed.ref                                                                    #';
    echo '################################################################################';
    echo;
    ./refal2 ../tests/speed.ref;
    echo;
    echo '################################################################################';
    echo '# moduleA.ref moduleB.ref moduleC.ref                                          #';
    echo '################################################################################';
    echo;
    ./refal2 ../tests/moduleA.ref ../tests/moduleB.ref ../tests/moduleC.ref;
    echo;
    echo '################################################################################';
    echo '# Fibonacci                                                                    #';
    echo '################################################################################';
    echo;
    ./refal2 ../tests/Fibonacci.ref;
    echo;
    echo '################################################################################';
    echo '# pi                                                                           #';
    echo '################################################################################';
    echo;
    ./refal2 ../tests/pi.ref
branches:
  only:
    - master
    - develop
